name: jobsupdev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nodejs=10.*
  - redis
  - cartopy
  - notebook
  - typescript
  - pip
  - pip:
    - git+https://github.com/UW-Hydro/pysumma.git@7480a12d40742d58629f2742ae7abc92131f831e
    - git+https://github.com/cybergis/job-supervisor-python-sdk.git@7fd2f3fba1b05e4c7f8e341ff2f557e83a3cf40f